name: Publish
description: "Publish a docker image to a registry"

inputs:
  user:
    description: "Docker username"
    required: true
  token:
    description: "Docker password"
    required: true
  image:
    description: "Name of the image to build"
    required: true
  tag:
    description: "Tag of the image to build"
    required: true

runs:
  using: composite
  steps:
    - name: Docker login
      shell: bash
      run: |
        echo "Logging in to docker"
        echo ${{inputs.token}} | docker login -u ${{ inputs.user }} --password-stdin &> /dev/null

    - name: Docker image upload
      shell: bash
      run: docker image push ${{ inputs.image }}:${{ inputs.tag }}

    - name: Docker logout
      if: success() || failure()
      shell: bash
      run: |
        echo "Logging out of docker"
        docker logout &> /dev/null
