name: Variables
description: "Set variables for use in other actions"

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: Actions/checkout@v3
      with:
        repository: ${{ github.repository }}
        ref: ${{ github.ref_name }}
        fetch-depth: 0     

    - name: Create variables
      shell: bash
      run: |
        echo "Exporting variables to Variables file"
        touch variables.txt
        echo "DLRS_NAME=${{ github.repository_owner }}/$(pwd | awk -F'/' '{print $NF}')" >> variables.txt
        echo "DLRS_VERSION=$(cat pyproject.toml | grep version | awk -F'=' '{print $2}' | sed 's/ \|"\|//g')" >> variables.txt
        echo "DLRS_LAST_VERSION=$(git tag --sort creatordate -l 'v*-RELEASE*' 'v*-RC*' --merged | tail -n 1)" >> variables.txt
    
    - name: Upload variables
      uses: actions/upload-artifact@v3
      with:
        name: variables.txt
        path: variables.txt