name: Variables
description: "Set variables for use in other actions"

runs:
  using: composite
  steps:
    - name: Setting variables
      shell: bash
      run: |
        echo "Setting variables in variables file"
        touch variables.txt
        echo -e DLRS_NAME=dlrs-$(basename `git rev-parse --show-toplevel`) >> variables.txt 
        echo -e DLRS_BRANCH=${{ github.ref_name }} >> variables.txt
        echo -e DLRS_VERSION=$(git tag --sort creatordate -l "v*-RELEASE*" --merged | tail -n 1) >> variables.txt
