name: Setup Buildx
author: Lucas Cantarelli
description: "Setup Buildx for docker build"

inputs:
  name:
    description: "Name of the builder"
    required: true

runs:
  using: composite
  steps:
    # Mostra informações do builder
    - name: Motd
      shell: bash
      run: |
        echo "::group::Buildx Info"
        echo "Name: ${{ inputs.name }}"
        echo "Driver: docker-container"
        echo "Flags: --buildkitd-flags --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host"
        echo "Use: True}"
        echo "::endgroup::"

    # Cria o builder
    - name: Create Buildx
      shell: bash        
      run: |
        echo "::group::Create Buildx"
        docker buildx create \
        --name ${{ inputs.name }} --driver docker-container --buildkitd-flags --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host --use
        echo "::endgroup::"
