name: Export Variables
description: "Export variables for use in other actions"

inputs:
  DLRS_ENV_FILE: 
    description: "File name"
    required: false
    default: variables.json

runs:
  using: composite
  steps:
    - name: Create File
      env:
        DLRS_ENV_FILE: ${{ inputs.DLRS_ENV_FILE }}
      shell: bash
      run: |
        echo "::notice title=Create file::Create ${{ env.DLRS_ENV_FILE }}"
        touch ${{ env.DLRS_ENV_FILE }}

    - name: Export variables
      shell: bash
      run: |
        echo "::group::Environment Variables"
        echo "DLRS_NAME=$(echo ${{ github.repository }} | awk -F'/' '{print $NF}')"  >> ${{ env.DLRS_ENV_FILE }}
        echo "DLRS_VERSION=$(cat dlrs-release.json | grep version | awk -F':' '{print $2}' | sed 's/ \|"\|//g' | awk -F'-' '{print $1}' | sed 's/[^0-9.]*//g' )"  >> ${{ env.DLRS_ENV_FILE }}
        echo "DLRS_REPOSITORY=${{ github.repository }}" >> ${{ env.DLRS_ENV_FILE }}
        echo "DLRS_BRANCH=$(echo ${{ github.ref }} | awk -F'/' '{print $NF}')" >> ${{ env.DLRS_ENV_FILE }}
        echo "DLRS_TAG=$(cat dlrs-release.json | grep version | awk -F':' '{print $2}' | sed 's/ \|"\|//g')"  >> ${{ env.DLRS_ENV_FILE }}
        echo "DLRS_SUFFIX=$(cat dlrs-release.json | grep version | awk -F':' '{print $2}' | sed 's/ \|"\|//g' | awk -F'-' '{print $2}' | sed 's/[^0-9.]*//g' )"  >> ${{ env.DLRS_ENV_FILE }}    
        cat ${{ env.DLRS_ENV_FILE }} | xargs -I {} echo "{}"
        echo "::endgroup::"

    - name: Upload variables
      uses: actions/upload-artifact@v3
      env:
        DLRS_ENV_FILE: ${{ inputs.DLRS_ENV_FILE }}
      with:
        name: ${{ env.DLRS_ENV_FILE }}
        path: ${{ env.DLRS_ENV_FILE }}