name: Load Variables
description: "Load variables for use in other actions"

runs:
  using: composite
  steps:
    - name: Download variables
      uses: actions/download-artifact@v3
      with:
        name: variables.txt
      
    - name: Set variables
      shell: bash
      run: |
        cat variables.txt | xargs -I {} echo "{}" >> $GITHUB_ENV