name: Load Variables
description: "Load variables for use in other actions"

inputs:
  env_file: 
    description: "File name"
    required: true

runs:
  using: composite
  steps:       
    - name: Download variables
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.env_file }}
      
    - name: Set variables
      shell: bash
      run: |
        echo "::group::Load Variables"
        cat ${{ inputs.env_file }} | xargs -I {} echo "{}" >> $GITHUB_ENV
        cat ${{ inputs.env_file }} | xargs -I {} echo "{}"
        echo "::endgroup::"