name: Versions
description: "Versioning for DLRS"

inputs:
  branch: 
    description: "Branch name"
    required: true
  tag: 
    description: "Tag name"
    required: true
  version:
    description: "Version name"
    required: true
  major:
    description: "Major version"
    required: false
  minor:
    description: "Minor version"
    required: false
    default: "false"
  patch:
    description: "Patch version"
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Versioning major
      shell: bash
      if: ${{ inputs.major == 'true' }}
      env:
        BRANCH: ${{ inputs.branch }}
        TAG: ${{ inputs.tag }}
        VERSION: ${{ inputs.version }}

      run: |
        echo "::group::Versioning major"
        echo "DLRS_VERSION=$( echo $VERSION | awk -F. '{print $1+1".0.0"}' )" >> $GITHUB_OUTPUT
        echo "DLRS_TAG=$( echo ${{ env.DLRS_VERSION }}-$( echo ${{ env.TAG }} | awk -F'-' '{print $2}' ))" >> $GITHUB_OUTPUT
        if [[ ${{ env.BRANCH }} == "main" ]]; then
            echo "DLRS_BRANCH=hotfix/${{ env.DLRS_VERSION }}" >> $GITHUB_OUTPUT
          elif [[ ${{ env.BRANCH }} == "develop" ]]; then
            echo "DLRS_BRANCH=release/${{ env.DLRS_VERSION }}" >> $GITHUB_OUTPUT
        fi
        echo "::endgroup::"

    - name: Versioning minor
      shell: bash
      if: ${{ inputs.minor == 'true' }}
      env:
        BRANCH: ${{ inputs.branch }}
        TAG: ${{ inputs.tag }}
        VERSION: ${{ inputs.version }}

      run: |
        echo "::group::Versioning minor"
        echo "DLRS_VERSION=$( echo $VERSION | awk -F. '{print $1"."$2+1".0"}' )" >> $GITHUB_OUTPUT
        echo "DLRS_TAG=$( echo ${{ env.DLRS_VERSION }}-$( echo ${{ env.TAG }} | awk -F'-' '{print $2}' ))" >> $GITHUB_OUTPUT
        if [[ ${{ env.BRANCH }} == "main" ]]; then
            echo "DLRS_BRANCH=hotfix/${{ env.DLRS_VERSION }}" >> $GITHUB_OUTPUT
          elif [[ ${{ env.BRANCH }} == "develop" ]]; then
            echo "DLRS_BRANCH=release/${{ env.DLRS_VERSION }}" >> $GITHUB_OUTPUT
        fi
        echo "::endgroup::"

    - name: Versioning patch
      shell: bash
      if: ${{ inputs.patch == 'true' }}
      env:
        BRANCH: ${{ inputs.branch }}
        TAG: ${{ inputs.tag }}
        VERSION: ${{ inputs.version }}

      run: |
        echo "::group::Versioning patch"
        echo "DLRS_VERSION=$( echo $VERSION | awk -F. '{print $1"."$2"."$3+1}' )" >> $GITHUB_OUTPUT
        echo "DLRS_TAG=$( echo ${{ env.DLRS_VERSION }}-$( echo ${{ env.TAG }} | awk -F'-' '{print $2}' ))" >> $GITHUB_OUTPUT
        if [[ ${{ env.BRANCH }} == "main" ]]; then
            echo "DLRS_BRANCH=hotfix/${{ env.DLRS_VERSION }}" >> $GITHUB_OUTPUT
          elif [[ ${{ env.BRANCH }} == "develop" ]]; then
            echo "DLRS_BRANCH=release/${{ env.DLRS_VERSION }}" >> $GITHUB_OUTPUT
        fi
        echo "::endgroup::"