name: Versions
description: "Versioning for DLRS"

inputs:
  branch: 
    description: "Branch name"
    required: true
  tag: 
    description: "Tag name"
    required: true
  version:
    description: "Version name"
    required: true
  major:
    description: "Major version"
    required: false
  minor:
    description: "Minor version"
    required: false
    default: "false"
  patch:
    description: "Patch version"
    required: false
    default: "false"

outputs:
  version:
    value: ${{ steps.set_outputs.outputs.version }}
    description: "Version name"
  tag:
    value: ${{ steps.set_outputs.outputs.tag }}
    description: "Tag name"
  branch:
    value: ${{ steps.set_outputs.outputs.branch }}
    description: "Branch name"

runs:
  using: composite
  steps:
    - name: Versioning major
      shell: bash
      if: ${{ inputs.major == 'true' }}
      env:
        DLRS_BRANCH: ${{ inputs.branch }}
        DLRS_TAG: ${{ inputs.tag }}
        DLRS_VERSION: ${{ inputs.version }}
      run: |
        echo "::group::Versioning major"
        echo "DLRS_NEXT_VERSION=$( echo ${{ env.DLRS_VERSION }} | awk -F. '{print $1+1".0.0"}')" >> $GITHUB_ENV
        echo "DLRS_NEXT_TAG=$( echo ${{ env.DLRS_VERSION }} | awk -F. '{print $1+1".0.0"}')-SNAPSHOT" >> $GITHUB_ENV
        if [[ ${{ env.DLRS_BRANCH }} == "main" ]]; then
            echo "DLRS_NEXT_BRANCH=hotfix/$( echo ${{ env.DLRS_VERSION }} | awk -F. '{print $1+1".0.0"}')" >> $GITHUB_ENV
          elif [[ ${{ env.DLRS_BRANCH }} == "develop" ]]; then
            echo "DLRS_NEXT_BRANCH=release/$( echo ${{ env.DLRS_VERSION }} | awk -F. '{print $1+1".0.0"}')" >> $GITHUB_ENV
        fi
        echo "::endgroup::"

    - name: Versioning minor
      shell: bash
      if: ${{ inputs.minor == 'true' }}
      env:
        DLRS_BRANCH: ${{ inputs.branch }}
        DLRS_TAG: ${{ inputs.tag }}
        DLRS_VERSION: ${{ inputs.version }}
      run: |
        echo "::group::Versioning minor"
        echo "DLRS_NEXT_VERSION=$( echo ${{ env.DLRS_VERSION }} | awk -F. '{print $1"."$2+1".0"}')"
        echo "DLRS_NEXT_TAG=$( echo ${{ env.DLRS_VERSION }} | awk -F. '{print $1"."$2+1".0"}')-$( echo ${{ env.DLRS_TAG }} | awk -F- '{print $2}' )"
        if [[ ${{ env.DLRS_BRANCH }} == "main" ]]; then
            echo "DLRS_NEXT_BRANCH=hotfix/$( echo ${{ env.DLRS_VERSION }} | awk -F. '{print $1"."$2+1".0"}')"
          elif [[ ${{ env.DLRS_BRANCH }} == "develop" ]]; then
            echo "DLRS_NEXT_BRANCH=release/$( echo ${{ env.DLRS_VERSION }} | awk -F. '{print $1"."$2+1".0"}')"
        fi
        echo "::endgroup::"

    - name: Versioning patch
      shell: bash
      if: ${{ inputs.patch == 'true' }}
      env:
        DLRS_BRANCH: ${{ inputs.branch }}
        DLRS_TAG: ${{ inputs.tag }}
        DLRS_VERSION: ${{ inputs.version }}
      run: |
        echo "::group::Versioning patch"
        echo "DLRS_NEXT_VERSION=$( echo ${{ env.DLRS_VERSION }} | awk -F. '{print $1"."$2"."$3+1}')"
        echo "DLRS_NEXT_TAG=$( echo ${{ env.DLRS_VERSION }} | awk -F. '{print $1"."$2"."$3+1}')-$( echo ${{ env.DLRS_TAG }} | awk -F- '{print $2}' )"
        if [[ ${{ env.DLRS_BRANCH }} == "main" ]]; then
            echo "DLRS_NEXT_BRANCH=hotfix/$( echo ${{ env.DLRS_VERSION }} | awk -F. '{print $1"."$2"."$3+1}')"
          elif [[ ${{ env.DLRS_BRANCH }} == "develop" ]]; then
            echo "DLRS_NEXT_BRANCH=release/$( echo ${{ env.DLRS_VERSION }} | awk -F. '{print $1"."$2"."$3+1}')"
        fi
        echo "::endgroup::"

    - name: Set outputs
      id: set_outputs
      shell: bash
      run: |
        echo "::group::Versioning outputs"
        echo "version=${{ env.DLRS_NEXT_VERSION }}" >> $GITHUB_OUTPUT
        echo "tag=${{ env.DLRS_NEXT_TAG }}" >> $GITHUB_OUTPUT
        echo "branch=${{ env.DLRS_NEXT_BRANCH }}" >> $GITHUB_OUTPUT
        echo "::endgroup::"