name: Versions
description: "Versioning for DLRS"

inputs:
  branch: 
    description: "Branch name"
    required: true
  tag: 
    description: "Tag name"
    required: true
  version:
    description: "Version name"
    required: true
  major:
    description: "Major version"
    required: false
  minor:
    description: "Minor version"
    required: false
  patch:
    description: "Patch version"
    required: false

runs:
  using: composite
  steps:
    - name: Versions
      shell: bash
      run: |
        echo ""