name: Versions
description: "Versioning for DLRS"

inputs:
  branch: 
    description: "Branch name"
    required: true
  tag: 
    description: "Tag name"
    required: true
  version:
    description: "Version name"
    required: true
  major:
    description: "Major version"
    required: false
  minor:
    description: "Minor version"
    required: false
    default: "false"
  patch:
    description: "Patch version"
    required: false
    default: "false"

outputs:
  version:
    value: ${{ steps.outputs.version }}
    description: "Version name"
  tag:
    value: ${{ steps.outputs.tag }}
    description: "Tag name"
  branch:
    value: ${{ steps.outputs.branch }}
    description: "Branch name"

runs:
  using: composite
  steps:
    - name: Versioning major
      shell: bash
      if: ${{ inputs.major == 'true' }}
      env:
        DLRS_BRANCH: ${{ inputs.branch }}
        DLRS_TAG: ${{ inputs.tag }}
        DLRS_VERSION: ${{ inputs.version }}
      run: |
        echo "::group::Versioning major"
        echo "version=$( echo ${{ env.DLRS_VERSION }} | awk -F. '{print $1+1".0.0"}')" >> $GITHUB_OUTPUT
        echo "tag=$( echo ${{ env.DLRS_VERSION }} | awk -F. '{print $1+1".0.0"}')-$( echo ${{ env.DLRS_TAG }} | awk -F- '{print $2}' )" >> $GITHUB_OUTPUT
        if [[ ${{ env.DLRS_BRANCH }} == "main" ]]; then
            echo "branch=hotfix/$( echo ${{ env.DLRS_VERSION }} | awk -F. '{print $1+1".0.0"}')" >> $GITHUB_OUTPUT
          elif [[ ${{ env.DLRS_BRANCH }} == "develop" ]]; then
            echo "branch=release/$( echo ${{ env.DLRS_VERSION }} | awk -F. '{print $1+1".0.0"}')" >> $GITHUB_OUTPUT
        fi
        echo "::endgroup::"

    - name: Versioning minor
      shell: bash
      if: ${{ inputs.minor == 'true' }}
      env:
        DLRS_BRANCH: ${{ inputs.branch }}
        DLRS_TAG: ${{ inputs.tag }}
        DLRS_VERSION: ${{ inputs.version }}
      run: |
        echo "::group::Versioning minor"
        echo "version=$( echo ${{ env.DLRS_VERSION }} | awk -F. '{print $1"."$2+1".0"}')" >> $GITHUB_OUTPUT
        echo "tag=$( echo ${{ env.DLRS_VERSION }} | awk -F. '{print $1"."$2+1".0"}')-$( echo ${{ env.DLRS_TAG }} | awk -F- '{print $2}' )" >> $GITHUB_OUTPUT
        if [[ ${{ env.DLRS_BRANCH }} == "main" ]]; then
            echo "branch=hotfix/$( echo ${{ env.DLRS_VERSION }} | awk -F. '{print $1"."$2+1".0"}')" >> $GITHUB_OUTPUT
          elif [[ ${{ env.DLRS_BRANCH }} == "develop" ]]; then
            echo "branch=release/$( echo ${{ env.DLRS_VERSION }} | awk -F. '{print $1"."$2+1".0"}')" >> $GITHUB_OUTPUT
        fi
        echo "::endgroup::"

    - name: Versioning patch
      shell: bash
      if: ${{ inputs.patch == 'true' }}
      env:
        DLRS_BRANCH: ${{ inputs.branch }}
        DLRS_TAG: ${{ inputs.tag }}
        DLRS_VERSION: ${{ inputs.version }}
      run: |
        echo "::group::Versioning patch"
        echo "version=$( echo ${{ env.DLRS_VERSION }} | awk -F. '{print $1"."$2"."$3+1}')" >> $GITHUB_OUTPUT
        echo "tag=$( echo ${{ env.DLRS_VERSION }} | awk -F. '{print $1"."$2"."$3+1}')-$( echo ${{ env.DLRS_TAG }} | awk -F- '{print $2}' )" >> $GITHUB_OUTPUT
        if [[ ${{ env.DLRS_BRANCH }} == "main" ]]; then
            echo "branch=hotfix/$( echo ${{ env.DLRS_VERSION }} | awk -F. '{print $1"."$2"."$3+1}')" >> $GITHUB_OUTPUT
          elif [[ ${{ env.DLRS_BRANCH }} == "develop" ]]; then
            echo "branch=release/$( echo ${{ env.DLRS_VERSION }} | awk -F. '{print $1"."$2"."$3+1}')" >> $GITHUB_OUTPUT
        fi
        echo "::endgroup::"