name: Versions
description: "Versioning for DLRS"

inputs:
  branch: 
    description: "Branch name"
    required: true
  tag: 
    description: "Tag name"
    required: true
  version:
    description: "Version name"
    required: true
  major:
    description: "Major version"
    required: false
  minor:
    description: "Minor version"
    required: false
    default: "false"
  patch:
    description: "Patch version"
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Versioning major
      shell: bash
      if: ${{ inputs.major == 'true' }}
      env:
        DLRS_BRANCH: ${{ inputs.branch }}
        DLRS_TAG: ${{ inputs.tag }}
        DLRS_VERSION: ${{ inputs.version }}
      run: |
        echo "::group::Versioning major"
        echo "DLRS_NEXT_VERSION=$( echo ${{ env.DLRS_VERSION }} | awk -F. '{print $1+1".0.0"}')"
        echo "DLRS_NEXT_TAG=$( echo ${{ env.DLRS_VERSION }} | awk -F. '{print $1+1".0.0"}')-$( echo ${{ env.DLRS_TAG }} | awk -F- '{print $2}' )"
        if [[ ${{ env.DLRS_BRANCH }} == "main" ]]; then
            echo "DLRS_NEXT_BRANCH=hotfix/$( echo ${{ env.DLRS_VERSION }} | awk -F. '{print $1+1".0.0"}')"
          elif [[ ${{ env.DLRS_BRANCH }} == "develop" ]]; then
            echo "DLRS_NEXT_BRANCH=release/$( echo ${{ env.DLRS_VERSION }} | awk -F. '{print $1+1".0.0"}')"
        fi
        echo "::endgroup::"

    - name: Versioning minor
      shell: bash
      if: ${{ inputs.minor == 'true' }}
      env:
        BRANCH: ${{ inputs.branch }}
        TAG: ${{ inputs.tag }}
        VERSION: ${{ inputs.version }}
      run: |
        echo "::group::Versioning minor"
        echo "DLRS_VERSION=$( echo $VERSION | awk -F. '{print $1"."$2+1".0"}' )"
        echo "DLRS_TAG=$( echo ${{ env.DLRS_VERSION }}-$( echo ${{ env.TAG }} | awk -F'-' '{print $2}' ))"
        if [[ ${{ env.BRANCH }} == "main" ]]; then
            echo "DLRS_BRANCH=hotfix/${{ env.DLRS_VERSION }}"
          elif [[ ${{ env.BRANCH }} == "develop" ]]; then
            echo "DLRS_BRANCH=release/${{ env.DLRS_VERSION }}"
        fi
        echo "::endgroup::"

    - name: Versioning patch
      shell: bash
      if: ${{ inputs.patch == 'true' }}
      env:
        BRANCH: ${{ inputs.branch }}
        TAG: ${{ inputs.tag }}
        VERSION: ${{ inputs.version }}
      run: |
        echo "::group::Versioning patch"
        echo "DLRS_VERSION=$( echo $VERSION | awk -F. '{print $1"."$2"."$3+1}' )"
        echo "DLRS_TAG=$( echo ${{ env.DLRS_VERSION }}-$( echo ${{ env.TAG }} | awk -F'-' '{print $2}' ))"
        if [[ ${{ env.BRANCH }} == "main" ]]; then
            echo "DLRS_BRANCH=hotfix/${{ env.DLRS_VERSION }}"
          elif [[ ${{ env.BRANCH }} == "develop" ]]; then
            echo "DLRS_BRANCH=release/${{ env.DLRS_VERSION }}"
        fi
        echo "::endgroup::"