name: Run Image
description: "Run a docker image"

inputs:
  DLRS_NAME:
    description: "Name of the docker image"
    required: true
  DLRS_VERSION:
    description: "Version of the docker image"
    required: true

runs:
  using: docker
  image: Dockerfile
  