name: Run Image
description: "Run a docker image"

runs:
  using: composite
  steps:
    - name: Docker image build
      shell: container
      run: |
        docker run -d --name ${{ env.DLRS_NAME }} ${{ env.DLRS_NAME }}:${{ env.DLRS_VERSION }}