name: Run Image
description: "Run a docker image"

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: Actions/checkout@v3
      with:
        repository: ${{ github.repository }}
        ref: ${{ github.ref_name }}
        fetch-depth: 0
      
    - name: Download variables
      uses: actions/download-artifact@v3
      with:
        name: variables.txt
      
    - name: Set variables
      shell: bash
      run: |
        cat variables.txt | xargs -I {} echo "{}" >> $GITHUB_ENV

    - name: Docker image run
      shell: bash
      run: |
        echo "Running docker image ${{ env.DLRS_REPOSITORY }}:${{ env.DLRS_VERSION }}" 
        docker run -it -d --name ${{ env.DLRS_NAME }} ${{ env.DLRS_REPOSITORY }}:${{ env.DLRS_VERSION }}
        sleep 5
        docker exec ${{ env.DLRS_NAME }} /bin/bash -c "cat /etc/motd" 