name: Docker run
description: "Run a docker image"

inputs:
  container:
    description: "Name of the container to run"
    required: true
  image:
    description: "Name of the image to build"
    required: true
  tag:
    description: "Tag of the image to build"
    required: true

runs:
  using: composite
  steps:
    - name: Docker Run
      shell: bash
      run: |
        echo "Running docker image ${{ inputs.container }}:${{ inputs.tag }}" 
        docker run -it -d --name ${{ inputs.container }} ${{ inputs.image }}:${{ inputs.tag }} &> /dev/null || true