name: Run Image
description: "Run a docker image"

runs:
  using: composite
  steps:
    - name: Docker image run
      shell: bash
      run: |
        echo "Running docker image ${{ env.DLRS_NAME }}:${{ env.DLRS_VERSION }}" 
        docker run -it -d --name ${{ env.DLRS_NAME }} ${{ env.DLRS_NAME }}:${{ env.DLRS_VERSION }}
        sleep 5
        docker exec ${{ env.DLRS_NAME }} /bin/bash -c "cat /etc/motd" 