name: Run Image
description: "Run a docker image"

inputs:
  DLRS_NAME:
    description: "Name of the docker image"
    required: true
  DLRS_VERSION:
    description: "Version of the docker image"
    required: true

runs:
  using: composite
  steps:
    - name: Docker image build
      shell: bash
      run: |
        echo "Running docker image ${{ env.DLRS_NAME }}:${{ env.DLRS_VERSION }}" 
        docker run -it ${{ env.DLRS_NAME }}:${{ env.DLRS_VERSION }} /bin/bash