name: Publish
description: "Publish a docker image to a registry"

inputs:
  DOCKER_USERNAME:
    description: "Docker username"
    required: true
  DOCKER_PASSWORD:
    description: "Docker password"
    required: true

runs:
  using: composite
  steps:
    - name: Docker login
      shell: bash
      run: |
        echo "Logging in to docker"
        echo ${{inputs.DOCKER_PASSWORD}} | docker login ${{ env.DRLS_REGISTRY }} -u ${{ github.actor }} --password-stdin

    - name: Docker image upload
      shell: bash
      run: |
        echo "Uploading docker to registry ${{ env.DLRS_NAME }}:${{ env.DLRS_VERSION }}"
        docker image push ${{ env.DLRS_NAME }}:${{ env.DLRS_VERSION }}

    - name: Docker logout
      if: success() || failure()
      shell: bash
      run: |
        echo "Logging out of docker"
        docker logout
