name: Publish
description: "Publish a docker image to a registry"

inputs:
  DOCKER_USERNAME:
    description: "Docker username"
    required: true
  DOCKER_PASSWORD:
    description: "Docker password"
    required: true
  DOCKER_REGISTRY:
    description: "Docker registry"
    required: true

runs:
  using: composite
  steps:
    - name: Docker verify
      shell: bash
      run: |
        docker pull ${{ inputs.DOCKER_REGISTRY }}/${{ env.DLRS_NAME }}:${{ env.DLRS_VERSION }} || true

    - name: Docker login
      if: failure()
      shell: bash
      run: |
        echo "Logging in to docker"
        echo ${{inputs.DOCKER_PASSWORD}} | docker login ${{ inputs.DOCKER_REGISTRY }} -u ${{inputs.DOCKER_USERNAME}} --password-stdin

    - name: Docker image tag
      if: success()
      shell: bash
      run: |
        echo "Tagging docker image ${{ env.DLRS_NAME }}:${{ env.DLRS_VERSION }}"
        docker tag ${{ inputs.DOCKER_REGISTRY }}/${{ env.DLRS_NAME }} ${{ inputs.DOCKER_REGISTRY }}/${{ env.DLRS_NAME }}:${{ env.DLRS_VERSION }}

    - name: Docker image upload
      if: success()
      shell: bash
      run: |
        echo "Uploading docker to registry ${{ inputs.DOCKER_REGISTRY }}/${{ env.DLRS_NAME }}:${{ env.DLRS_VERSION }}"
        docker image push --all-tags ${{ github.repository_owner }}/${{ env.DLRS_NAME }}

    - name: Docker logout
      if: success() || failure()
      shell: bash
      run: |
        echo "Logging out of docker"
        docker logout
