name: Publish
description: "Publish a docker image to a registry"

inputs:
  DOCKER_USERNAME:
    description: "Docker username"
    required: true
  DOCKER_PASSWORD:
    description: "Docker password"
    required: true

runs:
  using: composite
  steps:
    - name: Docker verify
      shell: bash
      id: docker_verify
      run: |
        echo "Logging out of docker";
        docker logout;
        docker pull ${{ env.DLRS_REPOSITORY }}:${{ env.DLRS_VERSION }} || true;

    - name: Docker login
      if: failure()
      shell: bash
      run: |
        echo "Logging in to docker"
        echo ${{inputs.DOCKER_PASSWORD}} | docker login -u ${{inputs.DOCKER_USERNAME}} --password-stdin

    - name: Docker image upload
      if: success()
      shell: bash
      run: |
        echo "Uploading docker image ${{ env.DLRS_NAME }}:${{ env.DLRS_VERSION }}"
        docker tag ${{ env.DLRS_NAME }}:${{ env.DLRS_VERSION }} ${{ env.DLRS_REPOSITORY }}:${{ env.DLRS_VERSION }}
        docker image push --all-tags ${{ github.repository_owner }}/${{ env.DLRS_NAME }}

    - name: Docker logout
      if: success() || failure()
      shell: bash
      run: |
        echo "Logging out of docker"
        docker logout
