name: Publish
description: "Publish a docker image to a registry"

inputs:
  DOCKER_USERNAME:
    description: "Docker username"
    required: true
  DOCKER_PASSWORD:
    description: "Docker password"
    required: true

runs:
  using: composite
  steps:
    - name: Docker logout
      shell: bash
      run: |
        echo "Logging out of docker";
        docker logout;

    - name: Docker login
      shell: bash
      run: |
        echo "Logging in to docker"
        echo ${{inputs.DOCKER_PASSWORD}} | docker login -u ${{inputs.DOCKER_USERNAME}} --password-stdin

    - name: Docker image upload
      shell: bash
      run: |
        echo "Uploading docker image ${{ env.DLRS_REPOSITORY }}:${{ env.DLRS_VERSION }}"
        docker tag ${{ env.DLRS_REPOSITORY }}:${{ env.DLRS_VERSION }} ${{ env.DLRS_REPOSITORY }}:${{ env.DLRS_VERSION }}
        docker push ${{ env.DLRS_REPOSITORY }}:${{ env.DLRS_VERSION }} --all-tags

    - name: Docker logout
      shell: bash
      run: |
        echo "Logging out of docker"
        docker logout
