name: Export Variables
description: "Export variables for use in other actions"

runs:
  using: composite
  steps:
    - name: Create variables
      shell: bash
      env:
        DLRS_NAME: ${{ github.repository }}
        DLRS_T3: $(echo ${{ github.repository }} | awk -F'/' '{print $NF}')

      run: |
        echo "::group::Environment Variables"
        echo "$DLRS_NAME"
        echo "$DLRS_T1"
        echo "$DLRS_T3"
        echo "::endgroup::" 