name: Export Variables
description: "Export variables for use in other actions"

runs:
  using: composite
  steps:
    - name: Create variables
      shell: bash
      run: |
        echo "::group::Environment Variables"
        echo $(export DLRS_NAME=$(echo ${{ github.repository }} | awk -F'/' '{print $NF}'))
        echo $(export DLRS_BRANCH=$(echo ${{ github.ref }} | awk -F'/' '{print $NF}'))
        echo $(export DLRS_ARTIFACT=$(echo ${{ github.repository }})/$(echo ${{ github.repository }} | awk -F'/' '{print $NF}'))
        echo $(export DLRS_VERSION=$(cat dlrs-release.json | grep version | awk -F':' '{print $2}' | sed 's/ \|"\|//g'))
        echo "::endgroup::"