name: Registry logout
author: Lucas Cantarelli
description: "Logout to a docker registry"

inputs:
  registry:
    description: "Registry to login"
    required: true
  username:
    description: "Username to login"
    required: true
  token:
    description: "Token to login"
    required: true
  

runs:
  using: composite
  steps:
    # Login to registry
    - name: Logout to registry
      shell: bash
      run: |
        echo "::group::Docker registry login"
        echo "Name: ${{ inputs.registry }}"
        echo ${{ inputs.token }} | docker logout ${{ inputs.registry }} -u ${{ inputs.username }} --password-stdin
        echo "::endgroup::"