name: Registry logout
author: Lucas Cantarelli
description: "Logout to a docker registry"

inputs:
  registry:
    description: "Registry to login"
    required: true
  

runs:
  using: composite
  steps:
    # Login to registry
    - name: Logout to registry
      shell: bash
      run: |
        echo "::group::Docker registry login"
        echo "Name: ${{ inputs.registry }}"
        docker logout ${{ inputs.registry }}
        echo "::endgroup::"