name: Load Variables
description: "Load variables for use in other actions"

inputs:
  ENV_FILE: 
    description: "File name"
    required: false
    default: variables.json

outputs:
  ENV_VARS:
    description: "Variables"
    value: ${{ steps.set-variables.outputs.Variables }}

runs:
  using: composite
  steps:
    - name: Download variables
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.ENV_FILE }}
      
    - name: Set variables
      id: set-variables
      shell: bash
      run: |
        echo "::group::Load Variables"
        echo "$(cat ${{ inputs.ENV_FILE }}) | xargs -I {}" >> $GITHUB_OUTPUT
        cat ${{ inputs.ENV_FILE }} | xargs -I {} echo "{}" >> $GITHUB_ENV
        cat ${{ inputs.ENV_FILE }} | xargs -I {} echo "{}"
        echo "::endgroup::"