name: Docker Deploy

on:
    workflow_call:

jobs:
    deploy:
        name: Deploy
        timeout-minutes: 10
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: Actions/checkout@v3
          with:
            repository: ${{ github.repository }}
            ref: ${{ github.ref_name }}
            fetch-depth: 0

        - name: Load variables
          uses: dolorestec/devops/.github/actions/variables/load@develop
            
        - name: Docker login
          run: |
            echo "Logging in to docker"
            echo ${{inputs.token}} | docker login -u ${{ inputs.user }} --password-stdin &> /dev/null

        - name: Build
          uses: dolorestec/devops/.github/actions/docker/buildx/build@develop
          with:
            image: ${{ env.DLRS_IMAGE_NAME }}
            tag: ${{ env.DLRS_IMAGE_TAG }}
            context: .
            dockerfile: Dockerfile
            push: true
            
        - name: Push
          run: |
            echo "Logging out of docker"
            docker logout &> /dev/null
