name: Docker Deploy
run-name: Deploy

on:
    workflow_call:

jobs:
    deploy:
        name: Deploy
        timeout-minutes: 10
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: Actions/checkout@v3
          with:
            repository: ${{ github.repository }}
            ref: ${{ github.ref_name }}
            fetch-depth: 0

        - name: Load variables
          uses: dolorestec/devops/.github/actions/variables/load@develop
            
        - name: Docker login
          run: |
            echo "Logging in to docker"
            echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ github.actor }} --password-stdin &> /dev/null

        - name: Build and push image
          uses: dolorestec/devops/.github/actions/docker/buildx/build@develop
          with:
            image: ${{ env.DLRS_IMAGE_NAME }}
            tag: ${{ env.DLRS_VERSION }}
            context: .
            dockerfile: Dockerfile
            push: true
            
        - name: Docker logout
          run: |
            echo "Logging out of docker"
            docker logout &> /dev/null
