name: Docker Deploy

on:
    workflow_call:

jobs:
    deploy:
        name: Deploy
        timeout-minutes: 10
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: Actions/checkout@v3
          with:
            repository: ${{ github.repository }}
            ref: ${{ github.ref_name }}
            fetch-depth: 0

        - name: Load variables
          uses: dolorestec/devops/.github/actions/variables/load@develop
            
        - name: Build and push
          uses: docker/build-push-action@v4
          with:
              context: .
              push: true
              tags: ${{ env.DLRS_IMAGE_NAME}}
              cache-from: type=gha
              cache-to: type=gha,mode=max

        - name: Push
          uses: dolorestec/devops/.github/actions/docker/push@develop
          with:
            user: ${{ github.actor }}
            token: ${{ secrets.DOCKER_TOKEN }}
            image: ${{ env.DLRS_IMAGE_NAME }}
            tag: ${{ env.DLRS_VERSION }}
