name: Docker teste

on:
    workflow_call:

jobs:
    build:
        name: Deploy
        timeout-minutes: 10
        runs-on: ubuntu-latest

        steps:
        -   name: Checkout
            uses: actions/checkout@v3

        -   name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2

        -   name: Login to Docker Hub
            uses: docker/login-action@v2
            with:
                username: "lucascantarelli"
                password: "#Psdw2021#"

        -   name: Build and push
            uses: docker/build-push-action@v4
            with:
                context: .
                push: true
                tags: ${{ env.DLRS_IMAGE_NAME}}
                cache-from: type=gha
                cache-to: type=gha,mode=max