name: Docker build
run-name: Docker build

on:
  workflow_call:

jobs:
  build:
    name: Build
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: Actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - name: Load variables
        uses: dolorestec/devops/.github/actions/variables/load@develop
            
      - name: Docker build
        run: |
          env
          
            