name: Environment
run-name: Environment

on:
    workflow_call:

jobs:
    changelog:
      name: Changelog
      timeout-minutes: 10
      runs-on: ubuntu-latest

      steps:
        - name: Changelog
          run: |
            echo "### Changelog" >> $GITHUB_STEP_SUMMARY
            
    variables:
        name: Variables
        timeout-minutes: 10
        runs-on: ubuntu-latest

        steps:
          - name: Changelog
            run: |
              echo "### Changelog" >> $GITHUB_STEP_SUMMARY

          - name: Checkout code
            uses: Actions/checkout@v3
            with:
              repository: ${{ github.repository }}
              ref: ${{ github.ref_name }}
              fetch-depth: 0
    
          - name: Export variables
            uses: dolorestec/devops/.github/actions/environment/variables/export@develop