name: Publish docker image

on:
  workflow_call:
      
jobs:
    push:
      name: Push
      timeout-minutes: 10
      runs-on: ubuntu-latest

      steps:
        - name: Docker build
          uses: dolorestec/devops/.github/actions/docker/build@v1
          with:
            cache-from: type=local,src=/tmp/.buildx-cache
            cache-to: type=local,dest=/tmp/.buildx-cache-new
            
        - name: Docker publish
          uses: dolorestec/devops/.github/actions/docker/publish@v1
          with:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
