name: Publish docker image

on:
  workflow_call:
      
jobs:
    push:
      name: Push
      timeout-minutes: 10
      runs-on: ubuntu-latest

      steps:
        - name: Docker build
          uses: dolorestec/devops/.github/actions/docker/build@main

        - name: Docker publish
          uses: dolorestec/devops/.github/actions/docker/publish@main
          with:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
