name: Publish docker image

on:
  workflow_call:
      
jobs:
    publish:
      name: Publish
      timeout-minutes: 10
      runs-on: ubuntu-latest

      steps:
        - name: Docker build
          uses: dolorestec/devops/.github/actions/docker/build@v1

        - name: Docker publish
          uses: dolorestec/devops/.github/actions/docker/publish@v1
          with:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
