name: Gitflow workflow
run-name: Gitflow

on:
    workflow_call:

jobs:
  create:
    name: Branch
    timeout-minutes: 10
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:
      - name: Checkout code
        env:
          REPOSITORY: ${{ github.repository }}
          REF: ${{ github.ref_name }}
          FETCH_DEPTH: 0
        uses: Actions/checkout@v3
        with:
          repository: ${{ env.REPOSITORY }}
          ref: ${{ env.REF }}
          fetch-depth: ${{ env.FETCH_DEPTH }}

      - name: Load variables
        id: variables
        uses: dolorestec/devops/.github/actions/variables/load@develop

      - name: Versioning
        id: versioning
        env:
          DLRS_BRANCH: ${{ env.DLRS_BRANCH }}
          DLRS_TAG: ${{ env.DLRS_TAG }}
          DLRS_VERSION: ${{ env.DLRS_VERSION }}
          DLRS_MAJOR: ${{ github.ref_name == 'develop' && 'true' || 'false' }}
          DLRS_MINOR: ${{ github.ref_name == 'main' && 'true' || 'false' }}
        uses: dolorestec/devops/.github/actions/versions@develop
        with:
          branch: ${{ env.DLRS_BRANCH }}
          tag: ${{ env.DLRS_TAG }}
          version: ${{ env.DLRS_VERSION }}
          major: ${{ env.DLRS_MAJOR }}
          minor: ${{ env.DLRS_MINOR }}

      - name: Create branch
        env:
          DLRS_BRANCH: ${{ env.DLRS_BRANCH }}
          DRLS_NEW_BRANCH: ${{ steps.versioning.outputs.branch }}
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "::group::Create branch"
          echo "Branch:${{ env.DLRS_BRANCH }} -> ${{ env.DRLS_NEW_BRANCH}}"

          git config --global user.email "${{ github.actor }}jpa@gmail.com"
          git config --global user.name ${{ github.actor }}
          
          git checkout -b ${{ env.DRLS_NEW_BRANCH}}
          git merge --no-ff ${{ env.DLRS_BRANCH }} -m "[CI] - Create branch ${{ env.DRLS_NEW_BRANCH }}"
          git push origin ${{ env.DRLS_NEW_BRANCH }}
          echo "::endgroup::"

      - name: Set version 
        env:
          DLRS_NAME: ${{ env.DLRS_NAME }}
          DLRS_BRANCH: ${{ env.DLRS_BRANCH }}
          DLRS_TAG: ${{ env.DLRS_TAG }}
          DLRS_NEW_BRANCH: ${{ steps.versioning.outputs.branch }}
          DLRS_NEW_TAG: ${{ steps.versioning.outputs.tag }}
        run: |
          echo "::group::Set version"
          git checkout ${{ env.DLRS_NEW_BRANCH }}
          sed -i 's/${{env.DLRS_TAG}}/${{ env.DLRS_NEW_TAG }}/g' "${{ env.DLRS_NAME }}.json"
          git add "${{ env.DLRS_NAME }}.json"
          git commit -m "[CI] - Create branch ${{ env.DLRS_NEW_BRANCH }}"
          git branch -D ${{ env.DLRS_BRANCH }}
          git push origin ${{ env.DLRS_NEW_BRANCH }}
          echo "::endgroup::"
          
      - if : ${{ failure() }}
        name: Rollback branch
        env:
          DLRS_BRANCH: ${{ env.DLRS_BRANCH }}
        run: |
          echo "::group::Rollback branch"
          git checkout ${{ env.DLRS_BRANCH }}
          git branch -D ${{ env.DLRS_BRANCH }}
          git push origin :${{ env.DLRS_BRANCH }}
          echo "::endgroup::"