name: Release Branch
run-name: Release Branch

on:
    workflow_call:

jobs:
    create:
        name: Create
        timeout-minutes: 10
        runs-on: ubuntu-latest
        environment: ${{ github.ref }}
        steps:
          - name: Checkout code
            uses: Actions/checkout@v3
            with:
              repository: ${{ github.repository }}
              ref: ${{ github.ref_name }}
              fetch-depth: 0

          - name: Create Release Branch
            run: |
                echo "release"