name: Gitflow workflow
run-name: Gitflow

on:
    workflow_call:

jobs:
  create:
    name: Branch
    timeout-minutes: 10
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    outputs:
      DLRS_NEW_BRANCH: ${{ steps.versioning.outputs.branch }}
      DLRS_NEW_TAG: ${{ steps.versioning.outputs.tag }}
      DLRS_NEW_VERSION: ${{ steps.versioning.outputs.version }}

    steps:
      - name: Checkout code
        env:
          REPOSITORY: ${{ github.repository }}
          REF: ${{ github.ref_name }}
          FETCH_DEPTH: 0
        uses: Actions/checkout@v3
        with:
          repository: ${{ env.REPOSITORY }}
          ref: ${{ env.REF }}
          fetch-depth: ${{ env.FETCH_DEPTH }}

      - name: Load variables
        id: variables
        uses: dolorestec/devops/.github/actions/variables/load@develop

      - name: Versioning
        id: versioning
        env:
          DLRS_BRANCH: ${{ env.DLRS_BRANCH }}
          DLRS_TAG: ${{ env.DLRS_TAG }}
          DLRS_VERSION: ${{ env.DLRS_VERSION }}
          DLRS_MAJOR: ${{ github.ref_name == 'develop' && 'true' || 'false' }}
          DLRS_MINOR: ${{ github.ref_name == 'main' && 'true' || 'false' }}
        uses: dolorestec/devops/.github/actions/versions@develop
        with:
          branch: ${{ env.DLRS_BRANCH }}
          tag: ${{ env.DLRS_TAG }}
          version: ${{ env.DLRS_VERSION }}
          major: ${{ env.DLRS_MAJOR }}
          minor: ${{ env.DLRS_MINOR }}

      - name: Create branch
        env:
          DLRS_NAME: ${{ env.DLRS_NAME }}
          DLRS_BRANCH: ${{ env.DLRS_BRANCH }}
          DLRS_TAG: ${{ env.DLRS_TAG }}
          DLRS_VERSION: ${{ env.DLRS_VERSION }}
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "::group::Create branch"
          echo "Branch:${{ env.DLRS_BRANCH }} -> ${{ steps.versioning.outputs.branch }}"
          echo "Tag: ${{ env.DLRS_TAG }} -> ${{ steps.versioning.outputs.tag }}"
          echo "Version: ${{ env.DLRS_VERSION }} -> ${{ steps.versioning.outputs.version }}"

          git config --global user.email "${{ github.actor }}jpa@gmail.com"
          git config --global user.name "${{ github.actor }}"
          
          git checkout -b "${{ steps.versioning.outputs.branch }}"
          git push origin ${{ steps.versioning.outputs.branch }}
          echo "::endgroup::"

  update:
    name: Update
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: create

    steps:
      - name: Checkout code
        env:
          REPOSITORY: ${{ github.repository }}
          REF: ${{ needs.create.outputs.DLRS_NEW_BRANCH }}
          FETCH_DEPTH: 0
        uses: Actions/checkout@v3
        with:
          repository: ${{ env.REPOSITORY }}
          ref: ${{ env.REF }}
          fetch-depth: ${{ env.FETCH_DEPTH }}
      
      - name: Load variables
        id: variables
        uses: dolorestec/devops/.github/actions/variables/load@develop

      - name: Set version 
        env:
          DLRS_NAME: ${{ env.DLRS_NAME }}
          DLRS_BRANCH: ${{ env.DLRS_BRANCH }}
          DLRS_TAG: ${{ env.DLRS_TAG }}
          DLRS_VERSION: ${{ env.DLRS_VERSION }}
          DLRS_NEW_BRANCH: ${{ needs.create.outputs.DLRS_NEW_BRANCH }}
          DLRS_NEW_TAG: ${{ needs.create.outputs.DLRS_NEW_TAG }}
          DLRS_NEW_VERSION: ${{ needs.create.outputs.DLRS_NEW_VERSION }}

        run: |
          echo "::group::Set version"
          git config --global user.email "${{ github.actor }}jpa@gmail.com"
          git config --global user.name "${{ github.actor }}"
          sed -i 's/${{env.DLRS_TAG}}/${{ env.DLRS_NEW_TAG }}/g' "${{ env.DLRS_NAME }}.json"
          git add "${{ env.DLRS_NAME }}.json"
          git commit -m "[CI] - Create branch ${{ env.DLRS_NEW_BRANCH }}"
          git push origin ${{ env.DLRS_NEW_BRANCH }}
          echo "::endgroup::"