name: Release
run-name: Release Branch

on:
    workflow_call:

jobs:
    create:
        name: Release Branch
        timeout-minutes: 10
        runs-on: ubuntu-latest
        environment: ${{ github.ref_name }}

        steps:
          - name: Checkout code
            uses: Actions/checkout@v3
            with:
              repository: ${{ github.repository }}
              ref: ${{ github.ref_name }}
              fetch-depth: 0

          - name: Release Branch
            run: |
                echo "release"