name: Release
run-name: Release Branch

on:
    workflow_call:

jobs:
    create:
        name: Release Branch
        timeout-minutes: 10
        runs-on: ubuntu-latest
        environment: ${{ github.ref_name }}

        steps:
          - name: Checkout code
            env:
              REPOSITORY: ${{ github.repository }}
              REF: ${{ github.ref_name }}
              FETCH_DEPTH: 0
            uses: Actions/checkout@v3
            with:
              repository: ${{ env.REPOSITORY }}
              ref: ${{ env.REF }}
              fetch-depth: ${{ env.FETCH_DEPTH }}
              
          - name: Release Branch
            run: |
                echo "release"