name: Setup environment
run-name: Environment

on:
    workflow_call:

jobs:
    variables:
        name: Variables
        timeout-minutes: 10
        runs-on: ubuntu-latest
  
        steps:
          - name: Checkout code
            env:
              REPOSITORY: ${{ github.repository }}
              REF: ${{ github.ref_name }}
              FETCH_DEPTH: 0
            uses: Actions/checkout@v3
            with:
              repository: ${{ env.REPOSITORY }}
              ref: ${{ env.REF }}
              fetch-depth: ${{ env.FETCH_DEPTH }}
  
          - name: Export variables
            uses: dolorestec/devops/.github/actions/variables/export@develop
            with:
              variables: |
                DLRS_NAME=${{ github.event.repository.name }}
                