name: Setup environment
run-name: Environment

on:
    workflow_call:

jobs:
    variables:
        name: Variables
        timeout-minutes: 10
        runs-on: ubuntu-latest
  
        steps:
          - name: Checkout code
            env:
              REPOSITORY: ${{ github.repository }}
              REF: ${{ github.ref_name }}
              FETCH_DEPTH: 0
            uses: Actions/checkout@v3
            with:
              repository: ${{ env.REPOSITORY }}
              ref: ${{ env.REF }}
              fetch-depth: ${{ env.FETCH_DEPTH }}
  
          - name: Export variables
            env:
              DLRS_VERSION_FILE: "${{ github.event.repository.name }}.json"
            uses: dolorestec/devops/.github/actions/variables/export@develop
            with:
              variables: |
                DLRS_NAME=${{ github.event.repository.name }}
                DLRS_VERSION=$(cat ${{env.DLRS_VERSION_FILE}} | grep version | awk -F':' '{print $2}' | sed 's/ \|"\|//g' | awk -F'-' '{print $1}' | sed 's/[^0-9.]*//g')
                DLRS_REPOSITORY=${{ github.repository }}
                DLRS_BRANCH=$(echo ${{ github.ref }} | awk -F'/' '{print $NF}')
                DLRS_TAG=$(cat ${{env.DLRS_VERSION_FILE}} | grep version | awk -F':' '{print $2}' | sed 's/ \|"\|//g')
                DLRS_SUFFIX=$( echo $(cat ${{env.DLRS_VERSION_FILE}} | grep version | awk -F':' '{print $2}' | sed 's/ \|"\|//g') | awk -F'-' '{print $2}')