name: Setup environment
run-name: Variables

on:
  workflow_call:
    inputs:
      env_file:
        type: string
        description: 'Environment file'
        required: true
        default: ${{ format('{0}.env',github.event.repository.name) }}
      version_file:
        type: string
        description: 'Project version file, ex: package.json, composer.json, pom.xml'
        required: true
        default: ${{ format('{0}.json',github.event.repository.name) }}
      variables:
          type: string
          description: 'Environment variables'
          required: true

jobs:
    variables:
        name: Variables
        timeout-minutes: 10
        runs-on: ubuntu-latest
        concurrency:
          group: ${{ github.ref }}
          cancel-in-progress: true
  
        steps:
          - name: Checkout code
            uses: Actions/checkout@v3
            with:
              repository: ${{ github.repository }}
              ref: ${{ github.ref_name }}
              fetch-depth: 0
        
          - name: Create File
            run: |
                echo "::notice title=Create file::Create ${{ inputs.env_file }}"
                touch ${{ inputs.env_file }}
          
          - name: Set variables
            run: |
              echo "::notice title=Set variables::Set variables"
              echo ${{ inputs.variables }}

          - name: Load variables
            run: |
              cat ${{ inputs.env_file }}

          - name: Upload artifact
            uses: actions/upload-artifact@v3
            with:
              name: ${{ inputs.env_file }}
              path: ${{ inputs.env_file }}
            