name: Validate Dockerfile

on:
    workflow_call:
      
jobs:
    variables:
      name: Variables
      timeout-minutes: 10
      runs-on: ubuntu-latest

      steps:
        - name: Export variables
          uses: dolorestec/devops/.github/actions/variables@v1

    test:
      name: Test
      timeout-minutes: 10
      runs-on: ubuntu-latest
      needs: variables
    
      steps:
        - name: Docker build
          uses: dolorestec/devops/.github/actions/docker/build@v1
          
        - name: Cache docker layers
          uses: actions/cache@v2
          with:
            path: /tmp/.buildx-cache
            key: ${{ runner.os }}-single-buildx-${{ github.sha }}
            restore-keys: |
              ${{ runner.os }}-single-buildx

        - name: Docker run
          uses: dolorestec/devops/.github/actions/docker/run@v1          