name: Validate

on:
    workflow_call:
      
jobs:
    variables:
        name: Variables
        timeout-minutes: 10
        runs-on: ubuntu-latest

        steps:         
        - name: Setting variables
          uses: dolorestec/devops/.github/actions/variables@v1


