name: Validate Dockerfile

on:
    workflow_call:
      
jobs:
    variables:
      name: Variables
      timeout-minutes: 10
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: Actions/checkout@v3
          with:
            repository: ${{ github.repository }}
            ref: ${{ github.ref_name }}
            fetch-depth: 0

        - name: Export variables
          uses: dolorestec/devops/.github/actions/variables/export@develop

    test:
      name: Test
      timeout-minutes: 10
      runs-on: ubuntu-latest
      needs: variables
    
      steps:
        - name: Checkout code
          uses: Actions/checkout@v3
          with:
            repository: ${{ github.repository }}
            ref: ${{ github.ref_name }}
            fetch-depth: 0

        - name: Load variables
          uses: dolorestec/devops/.github/actions/variables/load@develop

        - name: Docker build
          continue-on-error: true
          uses: dolorestec/devops/.github/actions/docker/build@develop
          with:
            image: ${{ env.DLRS_IMAGE_NAME }}
            tag: ${{ env.DLRS_VERSION }}
            dockerfile: "Dockerfile"
            context: "."

        - name: Docker run
          uses: dolorestec/devops/.github/actions/docker/run@develop  
          with:
            container: ${{ env.DLRS_NAME }}
            image: ${{ env.DLRS_IMAGE_NAME }}
            tag: ${{ env.DLRS_VERSION }}

        - name: Docker exec
          uses: dolorestec/devops/.github/actions/docker/exec@develop  
          with:
            container: ${{ env.DLRS_NAME }}
            command: "cat /etc/motd"

        - name: Cache save
          id: cache
          uses: actions/cache/save@v3
          with:
            path: ${{ github.workspace }}
            key: ${{ env.DLRS_NAME }}