name: Validate Dockerfile

on:
    workflow_call:
      
jobs:
    publish:
      name: Publish
      timeout-minutes: 10
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: Actions/checkout@v3
          with:
            repository: ${{ github.repository }}
            ref: ${{ github.ref_name }}
            fetch-depth: 0

        - name: Docker login
          run: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}