name: Validate Dockerfile

on:
    workflow_call:
      
jobs:
    variables:
      name: Variables
      timeout-minutes: 10
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: Actions/checkout@v3
          with:
            repository: ${{ github.repository }}
            ref: ${{ github.ref_name }}
            fetch-depth: 0

        - name: Export variables
          uses: dolorestec/devops/.github/actions/variables/export@develop

    test:
      name: Test
      timeout-minutes: 10
      runs-on: ubuntu-latest
      needs: variables
      if: ${{ github.job.cache.outputs.cache-hit != 'false'}}
    
      steps:
        - name: Checkout code
          uses: Actions/checkout@v3
          with:
            repository: ${{ github.repository }}
            ref: ${{ github.ref_name }}
            fetch-depth: 0

        - name: Load variables
          uses: dolorestec/devops/.github/actions/variables/load@develop

        - name: Cache
          id: cache
          uses: actions/cache@v3
          with:
            path: ${{ github.workspace }}
            key: ${{ env.DLRS_NAME }}-${{ env.DLRS_VERSION }}-${{github.sha}}
            restore-keys: |
              ${{ env.DLRS_NAME }}-${{ env.DLRS_VERSION }}-${{github.sha}}
              ${{ env.DLRS_NAME }}-${{ env.DLRS_VERSION }}-
              ${{ env.DLRS_NAME }}-

        - name: Docker build
          continue-on-error: true
          uses: dolorestec/devops/.github/actions/docker/build@develop
          with:
            image: ${{ env.DLRS_IMAGE_NAME }}
            tag: ${{ env.DLRS_VERSION }}
            context: .
            dockerfile: Dockerfile
            cache-to: type=gha,mode=max,ref=${{ env.DLRS_NAME }}-${{ env.DLRS_VERSION }}

        - name: Docker run
          uses: dolorestec/devops/.github/actions/docker/run@develop  
          with:
            container: ${{ env.DLRS_NAME }}
            image: ${{ env.DLRS_IMAGE_NAME }}
            tag: ${{ env.DLRS_VERSION }}

        - name: Docker exec
          uses: dolorestec/devops/.github/actions/docker/exec@develop  
          with:
            container: ${{ env.DLRS_NAME }}
            command: "cat /etc/motd"
        
        - if: ${{ steps.cache.outputs.cache-hit == 'true' }}
          name: Cache
          uses: actions/cache@v3
          with:
            path: ${{ github.workspace }}
            key: ${{ env.DLRS_NAME }}-${{ env.DLRS_VERSION }}-${{github.sha}}
            restore-keys: |
              ${{ env.DLRS_NAME }}-${{ env.DLRS_VERSION }}-${{github.sha}}
              ${{ env.DLRS_NAME }}-${{ env.DLRS_VERSION }}-
              ${{ env.DLRS_NAME }}-