name: Validate Dockerfile

on:
    workflow_call:
      
jobs:
    variables:
        name: Variables
        timeout-minutes: 10
        runs-on: ubuntu-latest

        steps:
        - name: Export variables
          uses: dolorestec/devops/.github/actions/variables@v1

    test:
        name: Test
        timeout-minutes: 10
        runs-on: ubuntu-latest
        needs: variables
    
        steps:
          - name: Checkout code
            uses: Actions/checkout@v3
            with:
              repository: ${{ github.repository }}
              ref: ${{ github.ref_name }}
              fetch-depth: 0
      
          - name: Download variables
            uses: actions/download-artifact@v3
            with:
              name: variables.txt
      
          - name: Set variables
            shell: bash
            run: |
              cat variables.txt | xargs -I {} echo "{}" >> $GITHUB_ENV

          - name: Docker build
            uses: dolorestec/devops/.github/actions/docker/build@v1

          - name: Docker push
            uses: dolorestec/devops/.github/actions/docker/upload@v1
            with:
              docker_username: ${{ secrets.DOCKER_USERNAME }}
              docker_password: ${{ secrets.DOCKER_PASSWORD }}
