name: Validate Dockerfile

on:
    workflow_call:
      
jobs:
    variables:
        name: Variables
        timeout-minutes: 10
        runs-on: ubuntu-latest

        steps:
        - name: Export variables
          uses: dolorestec/devops/.github/actions/variables@v1
        
        - name: Download variables
          uses: actions/download-artifact@v3
          with:
            name: variables.txt

        - name: Setting variables
          id: setting_variables
          run: |
            echo "::set-output name=variables::$(cat variables.txt | xargs -I {} echo '{}')"

        outputs:
            variables: ${{ steps.setting_variables.outputs.variables }}

    test:
        name: Test
        timeout-minutes: 10
        runs-on: ubuntu-latest
        needs: variables
        env:
            variables: ${{ needs.variables.outputs.variables }}

        steps:
        - name: Docker build
          #uses: dolorestec/devops/.github/actions/docker/build@v1
          run: |
            echo ${{ env.variables }}

        #- name: Docker run
        #  run: docker run --rm -it 